image: node:latest

stages:
  # - build
  # - test
  - deploy

# eslint:
#   stage: build
#   script:
#     - npm install
#     - npm run lint

# karma:
#   stage: test
#   script:
#     - npm install
#     - npm run unit

pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - mv dist public
  artifacts:
    paths:
    - public
  only:
  - master
