image: node:8.16

cache:
  paths:
  - node_modules/

deploy:
  only:
  - master
  script:
  - yarn
  - yarn lint
  - yarn build
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - rm dist/js/*.map
  - scp -o stricthostkeychecking=no -r dist/* $SSH_CONNECTION_STRING
