language: node_js
node_js:
  - '11.0.0'
cache:
  directories:
    - node_modules
install:
  - yarn install
  - yarn lint --no-fix
  - yarn build
  - yarn test:clear:snapshot
  - yarn test:unit --coverage
